services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: modernplayer-prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Kyiv
    volumes:
      - ./prowlarr:/config
    ports:
      - "127.0.0.1:9696:9696"
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: modernplayer-flaresolverr
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=none
      - TZ=Europe/Kyiv
    volumes:
      - ./flaresolverr:/config
    ports:
      - "127.0.0.1:8191:8191"
    restart: unless-stopped
